version: '3.2'

services:
  db:
    image: postgres:12.1
    container_name: learnengines_db
    environment:
      - POSTGRES_DB=learnengines_test
    ports:
      - "5432"

  redis:
    image: redis:5.0.7
    container_name: learnengines_redis
    ports:
      - "6379"

  test:
    build:
      context: .
      cache_from:
        - ${DOCKER_REGISTRY_HOST}/${DOCKER_IMAGE}:${BRANCH_TAG}-test
      args:
        - BUILD_ENV=test
        - RUBY_ENV=test
        - NODE_ENV=test
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_IMAGE}:${BRANCH_TAG}-test
    container_name: learnengines_test
    command: bin/test.sh
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - "ruby-bundle:/bundle"
      - "${PWD}/tmp/screenshots:/learnengines/tmp/screenshots"
      - "${PWD}/coverage:/learnengines/coverage"
      - "${PWD}/log:/learnengines/log"
    environment:
      - RACK_ENV=test
      - RAILS_ENV=test
      - NODE_ENV=test
      - DB_HOST=db
      - CI=$CI
      - TEST_RETRY=$TEST_RETRY
      - PORT=$PORT
      - DANGER_GITHUB_API_TOKEN=$DANGER_GITHUB_API_TOKEN

volumes:
  ruby-bundle:
